CLASS_LIST_FILE = "./class_list.json"
CLASS_REVIEWS_LIST_FILE = "./class_objs.json"
PROF_REVIEWS_LIST_FILE = "./prof_objs.json"
COMPILED_DATA_FILE = "./burnt-out-app/src/data/compiled_course_data.json"
CAB_URL = "https://cab.brown.edu/"
